package com.example.promptxo.ui.screens

import android.app.Activity
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.OpenInNew
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage
import coil.request.CachePolicy
import coil.request.ImageRequest
import com.example.promptxo.data.model.ImagePostItem
import com.example.promptxo.ui.PromptXoViewModel
import com.example.promptxo.ui.components.NativeAdSlotView
import com.example.ui.theme.PromptXoBorder
import com.example.ui.theme.PromptXoCardBg
import com.example.ui.theme.PromptXoDarkBg
import com.example.ui.theme.PromptXoPrimary
import com.example.ui.theme.PromptXoSearchBg
import com.example.ui.theme.PromptXoTextSecondary
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@Composable
fun ImageDetailScreen(
    imagePost: ImagePostItem,
    viewModel: PromptXoViewModel,
    onBackClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val activity = context as? Activity
    val scope = rememberCoroutineScope()

    // Prompt starts UNGENERATED as requested by user
    var isPromptGenerated by remember { mutableStateOf(false) }
    var isGenerating by remember { mutableStateOf(false) }
    var animatedPromptText by remember { mutableStateOf("") }
    val promptScrollState = rememberScrollState()

    fun copyToClipboard(text: String) {
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("AI Image Prompt", text)
        clipboard.setPrimaryClip(clip)
        Toast.makeText(context, "Image prompt copied to clipboard!", Toast.LENGTH_SHORT).show()
    }

    fun openExternalTool(url: String) {
        try {
            val safeUrl = if (url.startsWith("http://") || url.startsWith("https://")) url else "https://$url"
            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(safeUrl))
            context.startActivity(intent)
        } catch (e: Exception) {
            Toast.makeText(context, "Could not open tool link: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun generatePromptEffect() {
        scope.launch {
            isGenerating = true
            animatedPromptText = ""
            val words = imagePost.imageprompt.split(" ")
            var current = ""
            for (word in words) {
                current += if (current.isEmpty()) word else " $word"
                animatedPromptText = current
                // Auto scroll inside the box as prompt generates upward
                promptScrollState.scrollTo(promptScrollState.maxValue)
                delay(30)
            }
            isGenerating = false
            isPromptGenerated = true
        }
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(PromptXoDarkBg)
    ) {
        // Only ONE top back button in the Scaffold top bar, so inner redundant back button is removed
        LazyColumn(
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth(),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp)
        ) {
            // Main Image Card (matching screenshot 1000012995.jpg)
            item {
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 12.dp)
                        .aspectRatio(0.85f),
                    shape = RoundedCornerShape(20.dp),
                    colors = CardDefaults.cardColors(containerColor = PromptXoSearchBg),
                    border = CardDefaults.outlinedCardBorder().copy(brush = SolidColor(PromptXoBorder))
                ) {
                    AsyncImage(
                        model = ImageRequest.Builder(context)
                            .data(imagePost.thumbnail)
                            .crossfade(true)
                            .diskCachePolicy(CachePolicy.ENABLED)
                            .memoryCachePolicy(CachePolicy.ENABLED)
                            .networkCachePolicy(CachePolicy.ENABLED)
                            .build(),
                        contentDescription = imagePost.imagetitle,
                        contentScale = ContentScale.Crop,
                        modifier = Modifier.fillMaxSize()
                    )
                }
            }

            // Generated Prompt Container
            item {
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 18.dp),
                    shape = RoundedCornerShape(16.dp),
                    colors = CardDefaults.cardColors(containerColor = PromptXoCardBg),
                    border = CardDefaults.outlinedCardBorder().copy(brush = SolidColor(PromptXoBorder))
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(16.dp)
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                text = "Generated prompt",
                                color = Color.White,
                                fontSize = 16.sp,
                                fontWeight = FontWeight.Bold
                            )

                            if (isPromptGenerated && !isGenerating) {
                                IconButton(
                                    onClick = { generatePromptEffect() },
                                    modifier = Modifier.size(32.dp)
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.AutoAwesome,
                                        contentDescription = "Regenerate",
                                        tint = PromptXoPrimary,
                                        modifier = Modifier.size(20.dp)
                                    )
                                }
                            }
                        }

                        Spacer(modifier = Modifier.height(14.dp))

                        // If NOT generated yet: show "Generate Prompt" button
                        if (!isPromptGenerated && !isGenerating) {
                            Button(
                                onClick = { generatePromptEffect() },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(48.dp),
                                colors = ButtonDefaults.buttonColors(containerColor = PromptXoPrimary),
                                shape = RoundedCornerShape(12.dp)
                            ) {
                                Icon(
                                    imageVector = Icons.Default.AutoAwesome,
                                    contentDescription = "Generate",
                                    tint = Color.White,
                                    modifier = Modifier.size(18.dp)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "Generate Prompt",
                                    color = Color.White,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 15.sp
                                )
                            }
                        } else {
                            // Prompt Text Box
                            Text(
                                text = if (isGenerating) animatedPromptText else imagePost.imageprompt,
                                color = PromptXoTextSecondary,
                                fontSize = 13.sp,
                                lineHeight = 19.sp
                            )

                            Spacer(modifier = Modifier.height(18.dp))

                            // Action Buttons: Copy Prompt (with rewarded ad) & Try in Tool
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(8.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Button(
                                    onClick = {
                                        viewModel.adMobManager.showRewardedAd(
                                            activity = activity,
                                            title = "Watch Ad to Copy Image Prompt"
                                        ) {
                                            copyToClipboard(imagePost.imageprompt)
                                        }
                                    },
                                    modifier = Modifier
                                        .weight(1.2f)
                                        .height(46.dp),
                                    contentPadding = PaddingValues(horizontal = 10.dp, vertical = 0.dp),
                                    colors = ButtonDefaults.buttonColors(containerColor = PromptXoPrimary),
                                    shape = RoundedCornerShape(12.dp)
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.ContentCopy,
                                        contentDescription = "Copy",
                                        tint = Color.White,
                                        modifier = Modifier.size(16.dp)
                                    )
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Text(
                                        text = "Copy Prompt",
                                        color = Color.White,
                                        fontSize = 12.5.sp,
                                        fontWeight = FontWeight.SemiBold,
                                        maxLines = 1,
                                        softWrap = false
                                    )
                                }

                                OutlinedButton(
                                    onClick = { openExternalTool(imagePost.imagetoollink) },
                                    modifier = Modifier
                                        .weight(0.8f)
                                        .height(46.dp),
                                    contentPadding = PaddingValues(horizontal = 6.dp, vertical = 0.dp),
                                    shape = RoundedCornerShape(12.dp),
                                    border = ButtonDefaults.outlinedButtonBorder.copy(brush = SolidColor(PromptXoPrimary)),
                                    colors = ButtonDefaults.outlinedButtonColors(contentColor = Color.White)
                                ) {
                                    Text(
                                        text = imagePost.imagetoolname,
                                        fontSize = 11.5.sp,
                                        fontWeight = FontWeight.SemiBold,
                                        maxLines = 1,
                                        softWrap = false
                                    )
                                    Spacer(modifier = Modifier.width(4.dp))
                                    Icon(
                                        imageVector = Icons.AutoMirrored.Filled.OpenInNew,
                                        contentDescription = "Open",
                                        tint = PromptXoPrimary,
                                        modifier = Modifier.size(14.dp)
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Native Ad right beneath the prompt box as explicitly requested:
            // "اب جو باکس ہے، جنریٹو پرامپٹ والا باکس ہے، اس کے نیچے ہم نے نیٹو ایڈ دکھانا ہے ہم نے نیٹو ایڈ یوز کرنا ہے"
            item {
                Spacer(modifier = Modifier.height(16.dp))
                NativeAdSlotView(modifier = Modifier.fillMaxWidth())
                Spacer(modifier = Modifier.height(16.dp))
            }
        }
    }
}
