package com.example.promptxo.ui.screens

import android.app.Activity
import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.fadeIn
import androidx.compose.animation.slideInVertically
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.OpenInNew
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Image
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage
import coil.request.CachePolicy
import coil.request.ImageRequest
import com.example.promptxo.data.model.PostItem
import com.example.promptxo.ui.PromptXoViewModel
import com.example.promptxo.ui.components.NativeAdSlotView
import com.example.ui.theme.PromptXoBorder
import com.example.ui.theme.PromptXoCardBg
import com.example.ui.theme.PromptXoDarkBg
import com.example.ui.theme.PromptXoPrimary
import com.example.ui.theme.PromptXoSearchBg
import com.example.ui.theme.PromptXoSurface
import com.example.ui.theme.PromptXoTextMuted
import com.example.ui.theme.PromptXoTextPrimary
import com.example.ui.theme.PromptXoTextSecondary
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@Composable
fun PostDetailScreen(
    post: PostItem,
    viewModel: PromptXoViewModel,
    onBackClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val activity = context as? Activity
    val scope = rememberCoroutineScope()

    // Step 1 prompt generation states (simulating ChatGPT typewriter animation)
    var step1PromptGenerated by remember { mutableStateOf(false) }
    var step1AnimatedText by remember { mutableStateOf("") }
    var isStep1Generating by remember { mutableStateOf(false) }
    val step1ScrollState = rememberScrollState()

    // Step 2 prompt generation states (for optional step 2)
    var step2PromptGenerated by remember { mutableStateOf(false) }
    var step2AnimatedText by remember { mutableStateOf("") }
    var isStep2Generating by remember { mutableStateOf(false) }
    val step2ScrollState = rememberScrollState()

    fun copyToClipboard(text: String) {
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("AI Prompt", text)
        clipboard.setPrimaryClip(clip)
        Toast.makeText(context, "Prompt copied to clipboard!", Toast.LENGTH_SHORT).show()
    }

    fun openExternalLink(url: String) {
        try {
            val safeUrl = if (url.startsWith("http://") || url.startsWith("https://")) url else "https://$url"
            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(safeUrl))
            context.startActivity(intent)
        } catch (e: Exception) {
            Toast.makeText(context, "Could not open tool link: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    fun triggerTypewriterEffect(
        fullText: String,
        scrollState: androidx.compose.foundation.ScrollState,
        onUpdate: (String) -> Unit,
        onDone: () -> Unit
    ) {
        scope.launch {
            onUpdate("")
            val words = fullText.split(" ")
            var current = ""
            for (word in words) {
                current += if (current.isEmpty()) word else " $word"
                onUpdate(current)
                // Auto-scroll inside the prompt box to keep latest generated text visible
                scrollState.scrollTo(scrollState.maxValue)
                delay(35)
            }
            onDone()
        }
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(PromptXoDarkBg)
    ) {
        LazyColumn(
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth(),
            contentPadding = PaddingValues(bottom = 16.dp)
        ) {
            // Hero Image Header
            item {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp)
                        .height(260.dp)
                        .clip(RoundedCornerShape(20.dp))
                        .background(PromptXoSearchBg)
                ) {
                    AsyncImage(
                        model = ImageRequest.Builder(context)
                            .data(post.thumbnail)
                            .crossfade(true)
                            .diskCachePolicy(CachePolicy.ENABLED)
                            .memoryCachePolicy(CachePolicy.ENABLED)
                            .networkCachePolicy(CachePolicy.ENABLED)
                            .build(),
                        contentDescription = post.title,
                        contentScale = ContentScale.Crop,
                        modifier = Modifier.fillMaxSize()
                    )
                }
            }

            // Post Title & Description
            item {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 20.dp, vertical = 16.dp)
                ) {
                    Text(
                        text = post.title,
                        color = Color.White,
                        fontSize = 22.sp,
                        fontWeight = FontWeight.Bold
                    )
                    Spacer(modifier = Modifier.height(6.dp))
                    Text(
                        text = post.description,
                        color = PromptXoTextSecondary,
                        fontSize = 14.sp,
                        lineHeight = 20.sp
                    )
                }
            }

            // Step 1 Container
            item {
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp, vertical = 6.dp),
                    shape = RoundedCornerShape(18.dp),
                    colors = CardDefaults.cardColors(containerColor = PromptXoCardBg),
                    border = CardDefaults.outlinedCardBorder().copy(brush = SolidColor(PromptXoBorder))
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(16.dp)
                    ) {
                        // Header: Icon + Title
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Box(
                                modifier = Modifier
                                    .size(40.dp)
                                    .clip(RoundedCornerShape(10.dp))
                                    .background(PromptXoPrimary),
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Image,
                                    contentDescription = "Step 1",
                                    tint = Color.White,
                                    modifier = Modifier.size(24.dp)
                                )
                            }
                            Spacer(modifier = Modifier.width(12.dp))
                            Column {
                                Text(
                                    text = post.step1title,
                                    color = Color.White,
                                    fontSize = 16.sp,
                                    fontWeight = FontWeight.Bold
                                )
                                Text(
                                    text = post.step1description,
                                    color = PromptXoTextSecondary,
                                    fontSize = 12.sp
                                )
                            }
                        }

                        Spacer(modifier = Modifier.height(16.dp))

                        if (!step1PromptGenerated && !isStep1Generating) {
                            // "Generate Prompt" button before generation
                            Button(
                                onClick = {
                                    isStep1Generating = true
                                    triggerTypewriterEffect(
                                        fullText = post.step1prompt,
                                        scrollState = step1ScrollState,
                                        onUpdate = { step1AnimatedText = it },
                                        onDone = {
                                            isStep1Generating = false
                                            step1PromptGenerated = true
                                        }
                                    )
                                },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(48.dp),
                                colors = ButtonDefaults.buttonColors(containerColor = PromptXoPrimary),
                                shape = RoundedCornerShape(12.dp)
                            ) {
                                Icon(
                                    imageVector = Icons.Default.AutoAwesome,
                                    contentDescription = "Generate",
                                    tint = Color.White,
                                    modifier = Modifier.size(18.dp)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "Generate Prompt",
                                    color = Color.White,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 15.sp
                                )
                            }
                        } else {
                            // Dedicated Prompt Box of specific height (matching image height)
                            // Prompt generates and scrolls UP inside this box without pushing the screen down
                            Card(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(260.dp),
                                shape = RoundedCornerShape(16.dp),
                                colors = CardDefaults.cardColors(containerColor = PromptXoSearchBg),
                                border = CardDefaults.outlinedCardBorder().copy(brush = SolidColor(PromptXoBorder))
                            ) {
                                Column(
                                    modifier = Modifier
                                        .fillMaxSize()
                                        .padding(14.dp)
                                ) {
                                    Row(
                                        modifier = Modifier.fillMaxWidth(),
                                        horizontalArrangement = Arrangement.SpaceBetween,
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Text(
                                            text = "Generated Prompt",
                                            color = PromptXoPrimary,
                                            fontSize = 14.sp,
                                            fontWeight = FontWeight.Bold
                                        )
                                        if (isStep1Generating) {
                                            Text(
                                                text = "Typing...",
                                                color = PromptXoTextSecondary,
                                                fontSize = 11.sp
                                            )
                                        }
                                    }
                                    Spacer(modifier = Modifier.height(10.dp))
                                    Box(
                                        modifier = Modifier
                                            .weight(1f)
                                            .fillMaxWidth()
                                            .verticalScroll(step1ScrollState)
                                    ) {
                                        Text(
                                            text = if (isStep1Generating) step1AnimatedText else post.step1prompt,
                                            color = Color.White,
                                            fontSize = 13.sp,
                                            lineHeight = 20.sp
                                        )
                                    }
                                }
                            }

                            Spacer(modifier = Modifier.height(14.dp))

                            // Action buttons: Copy Prompt (Rewarded Ad) & Try in Tool
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.spacedBy(8.dp),
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                // Requirement: Rewarded ad when clicking "Copy Prompt"!
                                Button(
                                    onClick = {
                                        viewModel.adMobManager.showRewardedAd(
                                            activity = activity,
                                            title = "Watch Ad to Copy Prompt"
                                        ) {
                                            copyToClipboard(post.step1prompt)
                                        }
                                    },
                                    modifier = Modifier
                                        .weight(1.2f)
                                        .height(46.dp),
                                    contentPadding = PaddingValues(horizontal = 10.dp, vertical = 0.dp),
                                    colors = ButtonDefaults.buttonColors(containerColor = PromptXoPrimary),
                                    shape = RoundedCornerShape(12.dp)
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.ContentCopy,
                                        contentDescription = "Copy",
                                        tint = Color.White,
                                        modifier = Modifier.size(16.dp)
                                    )
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Text(
                                        text = "Copy Prompt",
                                        fontSize = 12.5.sp,
                                        fontWeight = FontWeight.SemiBold,
                                        maxLines = 1,
                                        softWrap = false
                                    )
                                }

                                // External Tool Link ("Try in Flow" / "Try in ChatGPT")
                                OutlinedButton(
                                    onClick = { openExternalLink(post.step1toollink) },
                                    modifier = Modifier
                                        .weight(0.8f)
                                        .height(46.dp),
                                    contentPadding = PaddingValues(horizontal = 6.dp, vertical = 0.dp),
                                    shape = RoundedCornerShape(12.dp),
                                    border = ButtonDefaults.outlinedButtonBorder.copy(brush = SolidColor(PromptXoPrimary)),
                                    colors = ButtonDefaults.outlinedButtonColors(contentColor = Color.White)
                                ) {
                                    Text(
                                        text = post.step1toolname,
                                        fontSize = 11.5.sp,
                                        fontWeight = FontWeight.SemiBold,
                                        maxLines = 1,
                                        softWrap = false
                                    )
                                    Spacer(modifier = Modifier.width(4.dp))
                                    Icon(
                                        imageVector = Icons.AutoMirrored.Filled.OpenInNew,
                                        contentDescription = "Open",
                                        tint = PromptXoPrimary,
                                        modifier = Modifier.size(14.dp)
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Step 2 Container (OPTIONAL as requested: "jo step 2 hoga hum use optional rakhenge")
            if (post.has2bean || post.step2title.isNotBlank()) {
                item {
                    Card(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 16.dp, vertical = 8.dp),
                        shape = RoundedCornerShape(18.dp),
                        colors = CardDefaults.cardColors(containerColor = PromptXoCardBg),
                        border = CardDefaults.outlinedCardBorder().copy(brush = SolidColor(PromptXoBorder))
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(16.dp)
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Box(
                                    modifier = Modifier
                                        .size(40.dp)
                                        .clip(RoundedCornerShape(10.dp))
                                        .background(Color(0xFF3B82F6)),
                                    contentAlignment = Alignment.Center
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.AutoAwesome,
                                        contentDescription = "Step 2",
                                        tint = Color.White,
                                        modifier = Modifier.size(24.dp)
                                    )
                                }
                                Spacer(modifier = Modifier.width(12.dp))
                                Column {
                                    Text(
                                        text = post.step2title.ifEmpty { "Step 2: Additional Video Prompt" },
                                        color = Color.White,
                                        fontSize = 16.sp,
                                        fontWeight = FontWeight.Bold
                                    )
                                    Text(
                                        text = post.step2description.ifEmpty { "Optional second phase prompt" },
                                        color = PromptXoTextSecondary,
                                        fontSize = 12.sp
                                    )
                                }
                            }

                            Spacer(modifier = Modifier.height(16.dp))

                            if (!step2PromptGenerated && !isStep2Generating) {
                                Button(
                                    onClick = {
                                        isStep2Generating = true
                                        triggerTypewriterEffect(
                                            fullText = post.step2prompt.ifEmpty { "Cinematic camera sweep with dynamic particles and volumetric light." },
                                            scrollState = step2ScrollState,
                                            onUpdate = { step2AnimatedText = it },
                                            onDone = {
                                                isStep2Generating = false
                                                step2PromptGenerated = true
                                            }
                                        )
                                    },
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .height(48.dp),
                                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF3B82F6)),
                                    shape = RoundedCornerShape(12.dp)
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.AutoAwesome,
                                        contentDescription = "Generate",
                                        tint = Color.White,
                                        modifier = Modifier.size(18.dp)
                                    )
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text(
                                        text = "Generate Step 2 Prompt",
                                        color = Color.White,
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 15.sp
                                    )
                                }
                            } else {
                                Card(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .height(260.dp),
                                    shape = RoundedCornerShape(16.dp),
                                    colors = CardDefaults.cardColors(containerColor = PromptXoSearchBg),
                                    border = CardDefaults.outlinedCardBorder().copy(brush = SolidColor(PromptXoBorder))
                                ) {
                                    Column(
                                        modifier = Modifier
                                            .fillMaxSize()
                                            .padding(14.dp)
                                    ) {
                                        Row(
                                            modifier = Modifier.fillMaxWidth(),
                                            horizontalArrangement = Arrangement.SpaceBetween,
                                            verticalAlignment = Alignment.CenterVertically
                                        ) {
                                            Text(
                                                text = "Generated Step 2 Prompt",
                                                color = Color(0xFF60A5FA),
                                                fontSize = 14.sp,
                                                fontWeight = FontWeight.Bold
                                            )
                                            if (isStep2Generating) {
                                                Text(
                                                    text = "Typing...",
                                                    color = PromptXoTextSecondary,
                                                    fontSize = 11.sp
                                                )
                                            }
                                        }
                                        Spacer(modifier = Modifier.height(10.dp))
                                        Box(
                                            modifier = Modifier
                                                .weight(1f)
                                                .fillMaxWidth()
                                                .verticalScroll(step2ScrollState)
                                        ) {
                                            Text(
                                                text = if (isStep2Generating) step2AnimatedText else post.step2prompt,
                                                color = Color.White,
                                                fontSize = 13.sp,
                                                lineHeight = 20.sp
                                            )
                                        }
                                    }
                                }

                                Spacer(modifier = Modifier.height(14.dp))

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Button(
                                        onClick = {
                                            viewModel.adMobManager.showRewardedAd(
                                                activity = activity,
                                                title = "Watch Ad to Copy Step 2 Prompt"
                                            ) {
                                                copyToClipboard(post.step2prompt)
                                            }
                                        },
                                        modifier = Modifier
                                            .weight(1.2f)
                                            .height(46.dp),
                                        contentPadding = PaddingValues(horizontal = 10.dp, vertical = 0.dp),
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF3B82F6)),
                                        shape = RoundedCornerShape(12.dp)
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.ContentCopy,
                                            contentDescription = "Copy",
                                            tint = Color.White,
                                            modifier = Modifier.size(16.dp)
                                        )
                                        Spacer(modifier = Modifier.width(6.dp))
                                        Text(
                                            text = "Copy Step 2",
                                            fontSize = 12.5.sp,
                                            fontWeight = FontWeight.SemiBold,
                                            maxLines = 1,
                                            softWrap = false
                                        )
                                    }

                                    if (post.step2toollink.isNotBlank()) {
                                        OutlinedButton(
                                            onClick = { openExternalLink(post.step2toollink) },
                                            modifier = Modifier
                                                .weight(0.8f)
                                                .height(46.dp),
                                            contentPadding = PaddingValues(horizontal = 6.dp, vertical = 0.dp),
                                            shape = RoundedCornerShape(12.dp),
                                            border = ButtonDefaults.outlinedButtonBorder.copy(brush = SolidColor(Color(0xFF3B82F6))),
                                            colors = ButtonDefaults.outlinedButtonColors(contentColor = Color.White)
                                        ) {
                                            Text(
                                                text = post.step2toolname.ifEmpty { "Open Tool" },
                                                fontSize = 11.5.sp,
                                                fontWeight = FontWeight.SemiBold,
                                                maxLines = 1,
                                                softWrap = false
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        // Native Ad at the bottom of the Detail screen (as in screenshot "Ad Loading...")
        NativeAdSlotView()
    }
}
